<a href="https://colab.research.google.com/github/ParamAhuja/DL_Notebooks/blob/main/HyperParamterTuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# df

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/ParamAhuja/DL_Notebooks/refs/heads/main/datasets/diabetes.csv")

In [2]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.corr()["Outcome"]

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [4]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [6]:
X.shape, y.shape

((768, 8), (768,))

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [8]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [9]:
model = Sequential()
model.add(Dense(32, activation="relu", input_dim=8))
model.add(Dense(16, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

model.compile(optimizer="Adam", loss="binary_crossentropy", metrics=["accuracy"])
model.fit(X_train, y_train, batch_size=32, epochs=100, verbose=1, validation_data = (X_test, y_test))

Epoch 1/100

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - accuracy: 0.6571 - loss: 0.6382 - val_accuracy: 0.6883 - val_loss: 0.6008
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7077 - loss: 0.5855 - val_accuracy: 0.7208 - val_loss: 0.5701
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7092 - loss: 0.5497 - val_accuracy: 0.7403 - val_loss: 0.5459
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7105 - loss: 0.5262 - val_accuracy: 0.7727 - val_loss: 0.5256
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7349 - loss: 0.5001 - val_accuracy: 0.7597 - val_loss: 0.5120
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7364 - loss: 0.4921 - val_accuracy: 0.7662 - val_loss: 0.5017
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7661 - loss: 0.4742 - val_accuracy: 0.7662 - val_loss: 0.4931
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7669 - loss: 0.4793 - val_accuracy: 0.7922 - val_loss: 0.4890
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7800 - loss: 0.4578 - val_accuracy: 0.7922 - val_loss: 0.4854
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7784 - loss: 0.4633 - val_accuracy: 0.7857 - val_loss: 0.4822
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.4395 - val_accuracy: 0.7922 - val_loss: 0.4791
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7680 - loss: 0.4620 - val_accuracy: 0.7922 - val_loss: 0.4797
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8022 - loss: 0.4363 - val_accuracy: 0.7857 - val_loss: 0.4791
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7988 - loss: 0.4418 - val_accuracy: 0.7922 - val_loss: 0.4806
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7870 - loss: 0.4401 - val_accuracy: 0.7922 - val_loss: 0.4814
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7889 - loss: 0.4249 - val_accuracy: 0.8052 - val_loss: 0.4796
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7875 - loss: 0.4419 - val_accuracy: 0.7987 - val_loss: 0.4770
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7709 - loss: 0.4459 - val_accuracy: 0.8052 - val_loss: 0.4755
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7922 - loss: 0.4275 - val_accuracy: 0.7987 - val_loss: 0.4762
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7714 - loss: 0.4675 - val_accuracy: 0.7987 - val_loss: 0.4757
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7912 - loss: 0.4270 - val_accuracy: 0.7987 - val_loss: 0.4745
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7750 - loss: 0.4521 - val_accuracy: 0.7857 - val_loss: 0.4778
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7833 - loss: 0.4551 - val_accuracy: 0.8117 - val_loss: 0.4752
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7751 - loss: 0.4451 - val_accuracy: 0.8052 - val_loss: 0.4737
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7903 - loss: 0.4122 - val_accuracy: 0.7987 - val_loss: 0.4779
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4381 - val_accuracy: 0.8052 - val_loss: 0.4742
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7942 - loss: 0.4207 - val_accuracy: 0.7922 - val_loss: 0.4737
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7693 - loss: 0.4214 - val_accuracy: 0.8117 - val_loss: 0.4733
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8050 - loss: 0.3935 - val_accuracy: 0.8117 - val_loss: 0.4733
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7728 - loss: 0.4303 - val_accuracy: 0.8117 - val_loss: 0.4717
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8071 - loss: 0.4040 - val_accuracy: 0.8117 - val_loss: 0.4718
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7923 - loss: 0.4073 - val_accuracy: 0.7922 - val_loss: 0.4725
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8128 - loss: 0.3978 - val_accuracy: 0.7987 - val_loss: 0.4715
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7881 - loss: 0.4026 - val_accuracy: 0.8117 - val_loss: 0.4694
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7938 - loss: 0.4257 - val_accuracy: 0.7987 - val_loss: 0.4694
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8073 - loss: 0.3912 - val_accuracy: 0.7922 - val_loss: 0.4705
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7776 - loss: 0.4181 - val_accuracy: 0.7987 - val_loss: 0.4695
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8009 - loss: 0.3950 - val_accuracy: 0.7987 - val_loss: 0.4698
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8099 - loss: 0.3918 - val_accuracy: 0.7987 - val_loss: 0.4724
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7827 - loss: 0.4128 - val_accuracy: 0.8052 - val_loss: 0.4737
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7729 - loss: 0.4181 - val_accuracy: 0.7987 - val_loss: 0.4701
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7844 - loss: 0.4020 - val_accuracy: 0.7922 - val_loss: 0.4690
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7929 - loss: 0.4042 - val_accuracy: 0.7987 - val_loss: 0.4707
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7889 - loss: 0.4001 - val_accuracy: 0.7987 - val_loss: 0.4677
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.8304 - loss: 0.3661 - val_accuracy: 0.7987 - val_loss: 0.4699
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7777 - loss: 0.3963 - val_accuracy: 0.7857 - val_loss: 0.4708
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8008 - loss: 0.3994 - val_accuracy: 0.7922 - val_loss: 0.4720
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7982 - loss: 0.3960 - val_accuracy: 0.7987 - val_loss: 0.4753
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8078 - loss: 0.4016 - val_accuracy: 0.7987 - val_loss: 0.4725
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7914 - loss: 0.3979 - val_accuracy: 0.7922 - val_loss: 0.4728
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8150 - loss: 0.3904 - val_accuracy: 0.7792 - val_loss: 0.4732
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8035 - loss: 0.3978 - val_accuracy: 0.7987 - val_loss: 0.4715
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8092 - loss: 0.3697 - val_accuracy: 0.8052 - val_loss: 0.4716
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8138 - loss: 0.3767 - val_accuracy: 0.7857 - val_loss: 0.4736
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7776 - loss: 0.4062 - val_accuracy: 0.7987 - val_loss: 0.4742
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.3999 - val_accuracy: 0.7922 - val_loss: 0.4743
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8138 - loss: 0.3770 - val_accuracy: 0.7987 - val_loss: 0.4749
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7995 - loss: 0.3878 - val_accuracy: 0.7987 - val_loss: 0.4755
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4027 - val_accuracy: 0.7987 - val_loss: 0.4758
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8133 - loss: 0.3520 - val_accuracy: 0.7987 - val_loss: 0.4758
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7996 - loss: 0.3841 - val_accuracy: 0.7987 - val_loss: 0.4787
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8017 - loss: 0.3891 - val_accuracy: 0.7987 - val_loss: 0.4772
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8038 - loss: 0.3898 - val_accuracy: 0.7987 - val_loss: 0.4774
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7926 - loss: 0.3959 - val_accuracy: 0.7922 - val_loss: 0.4780
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7933 - loss: 0.4122 - val_accuracy: 0.7987 - val_loss: 0.4802
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8173 - loss: 0.3637 - val_accuracy: 0.7857 - val_loss: 0.4799
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8033 - loss: 0.3856 - val_accuracy: 0.7987 - val_loss: 0.4812
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7855 - loss: 0.4123 - val_accuracy: 0.8052 - val_loss: 0.4781
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8268 - loss: 0.3828 - val_accuracy: 0.7987 - val_loss: 0.4797
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8051 - loss: 0.3909 - val_accuracy: 0.7987 - val_loss: 0.4803
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8148 - loss: 0.3618 - val_accuracy: 0.7987 - val_loss: 0.4824
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8147 - loss: 0.3661 - val_accuracy: 0.7987 - val_loss: 0.4829
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8064 - loss: 0.3603 - val_accuracy: 0.8052 - val_loss: 0.4819
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8213 - loss: 0.3923 - val_accuracy: 0.7987 - val_loss: 0.4814
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7923 - loss: 0.3928 - val_accuracy: 0.7857 - val_loss: 0.4834
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8162 - loss: 0.3675 - val_accuracy: 0.7987 - val_loss: 0.4827
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7807 - loss: 0.4021 - val_accuracy: 0.7987 - val_loss: 0.4851
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8203 - loss: 0.3629 - val_accuracy: 0.7922 - val_loss: 0.4849
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8071 - loss: 0.3782 - val_accuracy: 0.7857 - val_loss: 0.4854
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8180 - loss: 0.3647 - val_accuracy: 0.7922 - val_loss: 0.4864
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8172 - loss: 0.3908 - val_accuracy: 0.7857 - val_loss: 0.4919
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8344 - loss: 0.3758 - val_accuracy: 0.7987 - val_loss: 0.4930
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8274 - loss: 0.3620 - val_accuracy: 0.7922 - val_loss: 0.4892
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8095 - loss: 0.3807 - val_accuracy: 0.7987 - val_loss: 0.4893
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8188 - loss: 0.3470 - val_accuracy: 0.7922 - val_loss: 0.4890
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8316 - loss: 0.3716 - val_accuracy: 0.7922 - val_loss: 0.4914
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8350 - loss: 0.3425 - val_accuracy: 0.8052 - val_loss: 0.4905
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8303 - loss: 0.3578 - val_accuracy: 0.8052 - val_loss: 0.4903
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8136 - loss: 0.3787 - val_accuracy: 0.7987 - val_loss: 0.4913
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8137 - loss: 0.3867 - val_accuracy: 0.8052 - val_loss: 0.4924
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8399 - loss: 0.3408 - val_accuracy: 0.7987 - val_loss: 0.4961
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8039 - loss: 0.3789 - val_accuracy: 0.8052 - val_loss: 0.4946
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8121 - loss: 0.3707 - val_accuracy: 0.8052 - val_loss: 0.4937
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8097 - loss: 0.3564 - val_accuracy: 0.8052 - val_loss: 0.4970
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8308 - loss: 0.3679 - val_accuracy: 0.7987 - val_loss: 0.4956
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3600 - val_accuracy: 0.7987 - val_loss: 0.4995
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8235 - loss: 0.3911 - val_accuracy: 0.8052 - val_loss: 0.4984
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8289 - loss: 0.3654 - val_accuracy: 0.8052 - val_loss: 0.4988
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8181 - loss: 0.3718 - val_accuracy: 0.8052 - val_loss: 0.4987
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8326 - loss: 0.3552 - val_accuracy: 0.7987 - val_loss: 0.5035

# keras-tuner: hp.Choice
hyperparamter tuning for best optimizer

In [17]:
!pip install -q keras-tuner

In [18]:
# import keras_tuner as kt
import kerastuner as kt
# for some reason there are 2 modules, 1 might be deprecated

In [19]:
def build_model(hp):
  """conventional name for function is build_model
  paramter: hp (hyperparameter) object from keras tuner
  returns : model object optimized
  """
  # lets tune the optimizer
  model = Sequential()
  model.add(Dense(32, activation="relu", input_dim=8))
  model.add(Dense(16, activation="relu"))
  model.add(Dense(1, activation="sigmoid"))

  optimizer =hp.Choice("optimizer", ["adam", "rmsprop", "adagrad", "sgd", "adadelta"])
  model.compile(optimizer = optimizer,
                loss="binary_crossentropy",
                metrics=["accuracy"])
  return model

In [20]:
tuner = kt.RandomSearch(
    build_model,
    objective = "val_accuracy",
    max_trials = 5,
    directory = "mydir",
    project_name = "myproject1"
    )

In [21]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7077922224998474

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 24s

In [22]:
tuner.results_summary()

Results summary
Results in mydir/myproject1
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7857142686843872

Trial 1 summary
Hyperparameters:
optimizer: adam
Score: 0.7467532753944397

Trial 4 summary
Hyperparameters:
optimizer: sgd
Score: 0.7077922224998474

Trial 0 summary
Hyperparameters:
optimizer: adadelta
Score: 0.551948070526123

Trial 2 summary
Hyperparameters:
optimizer: adagrad
Score: 0.4610389471054077

In [23]:
tuner.get_best_hyperparameters()[0]

In [24]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [25]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 8 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [26]:
model.fit(X_train, y_train, batch_size=32, epochs=100, verbose=1, validation_data = (X_test, y_test), initial_epoch = 5)
# initial epochs to start from where it stopped in tuner (5 done)

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - accuracy: 0.7759 - loss: 0.5183 - val_accuracy: 0.7987 - val_loss: 0.4912
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7682 - loss: 0.5049 - val_accuracy: 0.8052 - val_loss: 0.4742
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7853 - loss: 0.4862 - val_accuracy: 0.7987 - val_loss: 0.4667
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7957 - loss: 0.4554 - val_accuracy: 0.8052 - val_loss: 0.4602
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7908 - loss: 0.4548 - val_accuracy: 0.8117 - val_loss: 0.4579
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7735 - loss: 0.4541 - val_accuracy: 0.8182 - val_loss: 0.4548
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7464 - loss: 0.4741 - val_accuracy: 0.8182 - val_loss: 0.4542
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7451 - loss: 0.4865 - val_accuracy: 0.8117 - val_loss: 0.4562
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7647 - loss: 0.4480 - val_accuracy: 0.8182 - val_loss: 0.4544
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7948 - loss: 0.4175 - val_accuracy: 0.8182 - val_loss: 0.4543
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7986 - loss: 0.4269 - val_accuracy: 0.7987 - val_loss: 0.4524
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7758 - loss: 0.4255 - val_accuracy: 0.8117 - val_loss: 0.4527
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7831 - loss: 0.4398 - val_accuracy: 0.8182 - val_loss: 0.4534
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7669 - loss: 0.4628 - val_accuracy: 0.8117 - val_loss: 0.4527
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7860 - loss: 0.4478 - val_accuracy: 0.8182 - val_loss: 0.4530
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7965 - loss: 0.4108 - val_accuracy: 0.8052 - val_loss: 0.4566
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7725 - loss: 0.4340 - val_accuracy: 0.8182 - val_loss: 0.4542
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7770 - loss: 0.4429 - val_accuracy: 0.8182 - val_loss: 0.4529
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7612 - loss: 0.4570 - val_accuracy: 0.8247 - val_loss: 0.4532
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7809 - loss: 0.3993 - val_accuracy: 0.8182 - val_loss: 0.4563
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7760 - loss: 0.4398 - val_accuracy: 0.8182 - val_loss: 0.4570
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7845 - loss: 0.4182 - val_accuracy: 0.8247 - val_loss: 0.4563
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8085 - loss: 0.4056 - val_accuracy: 0.8182 - val_loss: 0.4550
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7724 - loss: 0.4298 - val_accuracy: 0.8182 - val_loss: 0.4564
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7666 - loss: 0.4381 - val_accuracy: 0.8182 - val_loss: 0.4549
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7825 - loss: 0.4209 - val_accuracy: 0.8182 - val_loss: 0.4556
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7569 - loss: 0.4442 - val_accuracy: 0.8182 - val_loss: 0.4544
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7684 - loss: 0.4289 - val_accuracy: 0.8182 - val_loss: 0.4553
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7699 - loss: 0.4334 - val_accuracy: 0.8182 - val_loss: 0.4564
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7722 - loss: 0.4128 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7864 - loss: 0.4062 - val_accuracy: 0.8247 - val_loss: 0.4566
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7942 - loss: 0.4119 - val_accuracy: 0.8182 - val_loss: 0.4552
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7825 - loss: 0.4281 - val_accuracy: 0.8182 - val_loss: 0.4555
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7960 - loss: 0.4084 - val_accuracy: 0.8182 - val_loss: 0.4559
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7863 - loss: 0.4347 - val_accuracy: 0.8182 - val_loss: 0.4580
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7959 - loss: 0.4012 - val_accuracy: 0.8247 - val_loss: 0.4573
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7923 - loss: 0.4353 - val_accuracy: 0.8247 - val_loss: 0.4581
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7870 - loss: 0.4523 - val_accuracy: 0.8247 - val_loss: 0.4606
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7845 - loss: 0.4182 - val_accuracy: 0.8247 - val_loss: 0.4602
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7750 - loss: 0.4031 - val_accuracy: 0.8117 - val_loss: 0.4608
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7888 - loss: 0.4253 - val_accuracy: 0.8247 - val_loss: 0.4613
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4156 - val_accuracy: 0.8247 - val_loss: 0.4615
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8082 - loss: 0.4095 - val_accuracy: 0.7987 - val_loss: 0.4640
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4044 - val_accuracy: 0.8247 - val_loss: 0.4616
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7779 - loss: 0.4108 - val_accuracy: 0.8247 - val_loss: 0.4600
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3926 - val_accuracy: 0.7987 - val_loss: 0.4616
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8063 - loss: 0.3950 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7741 - loss: 0.4235 - val_accuracy: 0.8052 - val_loss: 0.4623
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8059 - loss: 0.4152 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7766 - loss: 0.4316 - val_accuracy: 0.8052 - val_loss: 0.4627
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7870 - loss: 0.4143 - val_accuracy: 0.8182 - val_loss: 0.4615
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7945 - loss: 0.4182 - val_accuracy: 0.8052 - val_loss: 0.4609
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8329 - loss: 0.4020 - val_accuracy: 0.8052 - val_loss: 0.4622
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4040 - val_accuracy: 0.8182 - val_loss: 0.4611
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7800 - loss: 0.4140 - val_accuracy: 0.8117 - val_loss: 0.4619
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8129 - loss: 0.4071 - val_accuracy: 0.8117 - val_loss: 0.4610
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8332 - loss: 0.3919 - val_accuracy: 0.8052 - val_loss: 0.4617
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8185 - loss: 0.3956 - val_accuracy: 0.8117 - val_loss: 0.4626
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7919 - loss: 0.4226 - val_accuracy: 0.7987 - val_loss: 0.4642
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8210 - loss: 0.4063 - val_accuracy: 0.7987 - val_loss: 0.4650
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8064 - loss: 0.4123 - val_accuracy: 0.7922 - val_loss: 0.4655
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7944 - loss: 0.4272 - val_accuracy: 0.7922 - val_loss: 0.4674
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8087 - loss: 0.3798 - val_accuracy: 0.8052 - val_loss: 0.4674
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8227 - loss: 0.4009 - val_accuracy: 0.7987 - val_loss: 0.4689
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8011 - loss: 0.4181 - val_accuracy: 0.8052 - val_loss: 0.4684
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8305 - loss: 0.3823 - val_accuracy: 0.7987 - val_loss: 0.4702
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8035 - loss: 0.4016 - val_accuracy: 0.7922 - val_loss: 0.4686
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8095 - loss: 0.4010 - val_accuracy: 0.7987 - val_loss: 0.4703
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7960 - loss: 0.4064 - val_accuracy: 0.7987 - val_loss: 0.4697
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8244 - loss: 0.3828 - val_accuracy: 0.7987 - val_loss: 0.4705
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8291 - loss: 0.3839 - val_accuracy: 0.7922 - val_loss: 0.4717
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8070 - loss: 0.3983 - val_accuracy: 0.7987 - val_loss: 0.4706
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.8240 - loss: 0.3900 - val_accuracy: 0.7987 - val_loss: 0.4707
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8256 - loss: 0.3818 - val_accuracy: 0.8052 - val_loss: 0.4703
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8201 - loss: 0.3914 - val_accuracy: 0.7987 - val_loss: 0.4668
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8070 - loss: 0.3888 - val_accuracy: 0.8052 - val_loss: 0.4660
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8265 - loss: 0.3743 - val_accuracy: 0.7792 - val_loss: 0.4681
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8447 - loss: 0.3472 - val_accuracy: 0.7857 - val_loss: 0.4686
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8203 - loss: 0.3967 - val_accuracy: 0.7922 - val_loss: 0.4713
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8061 - loss: 0.3810 - val_accuracy: 0.7987 - val_loss: 0.4699
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8035 - loss: 0.4075 - val_accuracy: 0.7922 - val_loss: 0.4738
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8175 - loss: 0.3917 - val_accuracy: 0.7792 - val_loss: 0.4743
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8161 - loss: 0.3853 - val_accuracy: 0.8052 - val_loss: 0.4726
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8279 - loss: 0.3791 - val_accuracy: 0.7987 - val_loss: 0.4752
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3864 - val_accuracy: 0.7922 - val_loss: 0.4743
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8172 - loss: 0.3879 - val_accuracy: 0.7857 - val_loss: 0.4769
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8214 - loss: 0.3695 - val_accuracy: 0.7987 - val_loss: 0.4753
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8287 - loss: 0.3624 - val_accuracy: 0.7987 - val_loss: 0.4735
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8368 - loss: 0.3582 - val_accuracy: 0.7987 - val_loss: 0.4727
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8513 - loss: 0.3631 - val_accuracy: 0.7922 - val_loss: 0.4732
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8112 - loss: 0.3988 - val_accuracy: 0.7987 - val_loss: 0.4743
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8291 - loss: 0.3788 - val_accuracy: 0.7922 - val_loss: 0.4793
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8363 - loss: 0.3464 - val_accuracy: 0.8052 - val_loss: 0.4769
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8386 - loss: 0.3734 - val_accuracy: 0.8052 - val_loss: 0.4775
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8410 - loss: 0.3485 - val_accuracy: 0.8052 - val_loss: 0.4773

# keras-tuner: hp.Int
hyperparamter tuning for number of nodes

In [27]:
def build_model(hp):
  model = Sequential()
  units = hp.Int("units", min_value=8, max_value=128, step=8)
  model.add(Dense(units=units, activation="relu", input_dim=8))
  model.add(Dense(1, activation="sigmoid"))

  model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])
  return model

In [28]:
tuner = kt.RandomSearch(
    build_model,
    objective = "val_accuracy",
    max_trials = 5,
    directory = "mydir",
    project_name = "myproject2"
)

**Analyze the directory**

In [29]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 05s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 17s

In [30]:
tuner.results_summary()

Results summary
Results in mydir/myproject2
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 1 summary
Hyperparameters:
units: 96
Score: 0.8051947951316833

Trial 4 summary
Hyperparameters:
units: 80
Score: 0.7922077775001526

Trial 0 summary
Hyperparameters:
units: 48
Score: 0.7857142686843872

Trial 2 summary
Hyperparameters:
units: 8
Score: 0.6428571343421936

Trial 3 summary
Hyperparameters:
units: 16
Score: 0.6363636255264282

In [31]:
tuner.get_best_hyperparameters()[0].values

{'units': 96}

In [32]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.11/dist-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [33]:
model.fit(X_train, y_train, batch_size=32, epochs=100, verbose=1, validation_data = (X_test, y_test), initial_epoch = 5)

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7477 - loss: 0.5325 - val_accuracy: 0.8052 - val_loss: 0.4910
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7884 - loss: 0.4822 - val_accuracy: 0.7987 - val_loss: 0.4788
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7742 - loss: 0.4973 - val_accuracy: 0.7922 - val_loss: 0.4713
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4846 - val_accuracy: 0.7987 - val_loss: 0.4666
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4559 - val_accuracy: 0.8052 - val_loss: 0.4647
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7780 - loss: 0.4487 - val_accuracy: 0.8247 - val_loss: 0.4645
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7701 - loss: 0.4696 - val_accuracy: 0.8247 - val_loss: 0.4634
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4560 - val_accuracy: 0.8117 - val_loss: 0.4634
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8023 - loss: 0.4433 - val_accuracy: 0.8117 - val_loss: 0.4626
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7946 - loss: 0.4420 - val_accuracy: 0.8247 - val_loss: 0.4641
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7885 - loss: 0.4360 - val_accuracy: 0.8182 - val_loss: 0.4627
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7709 - loss: 0.4650 - val_accuracy: 0.8247 - val_loss: 0.4639
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7760 - loss: 0.4794 - val_accuracy: 0.8247 - val_loss: 0.4630
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7945 - loss: 0.4403 - val_accuracy: 0.8182 - val_loss: 0.4624
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7480 - loss: 0.4727 - val_accuracy: 0.8182 - val_loss: 0.4620
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7763 - loss: 0.4485 - val_accuracy: 0.8182 - val_loss: 0.4622
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7839 - loss: 0.4279 - val_accuracy: 0.8117 - val_loss: 0.4613
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7798 - loss: 0.4677 - val_accuracy: 0.8117 - val_loss: 0.4607
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8063 - loss: 0.4152 - val_accuracy: 0.8182 - val_loss: 0.4628
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7862 - loss: 0.4208 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7705 - loss: 0.4719 - val_accuracy: 0.8117 - val_loss: 0.4629
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7896 - loss: 0.4487 - val_accuracy: 0.8182 - val_loss: 0.4654
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7892 - loss: 0.4353 - val_accuracy: 0.8117 - val_loss: 0.4671
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7887 - loss: 0.4376 - val_accuracy: 0.8117 - val_loss: 0.4650
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7849 - loss: 0.4352 - val_accuracy: 0.8182 - val_loss: 0.4638
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7914 - loss: 0.4118 - val_accuracy: 0.8247 - val_loss: 0.4626
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4157 - val_accuracy: 0.8117 - val_loss: 0.4634
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7951 - loss: 0.4362 - val_accuracy: 0.8182 - val_loss: 0.4629
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7832 - loss: 0.4177 - val_accuracy: 0.8247 - val_loss: 0.4616
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7579 - loss: 0.4437 - val_accuracy: 0.8247 - val_loss: 0.4628
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8014 - loss: 0.4240 - val_accuracy: 0.8247 - val_loss: 0.4623
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7861 - loss: 0.4242 - val_accuracy: 0.8117 - val_loss: 0.4646
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7968 - loss: 0.4057 - val_accuracy: 0.8247 - val_loss: 0.4632
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7946 - loss: 0.4223 - val_accuracy: 0.8182 - val_loss: 0.4650
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7874 - loss: 0.4239 - val_accuracy: 0.8182 - val_loss: 0.4635
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8004 - loss: 0.4330 - val_accuracy: 0.8117 - val_loss: 0.4639
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7788 - loss: 0.4411 - val_accuracy: 0.8117 - val_loss: 0.4650
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7930 - loss: 0.4276 - val_accuracy: 0.8117 - val_loss: 0.4644
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3823 - val_accuracy: 0.8117 - val_loss: 0.4643
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8246 - loss: 0.3970 - val_accuracy: 0.8117 - val_loss: 0.4656
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8110 - loss: 0.4116 - val_accuracy: 0.8182 - val_loss: 0.4628
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4140 - val_accuracy: 0.8182 - val_loss: 0.4639
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7837 - loss: 0.4317 - val_accuracy: 0.8052 - val_loss: 0.4634
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7994 - loss: 0.4282 - val_accuracy: 0.8182 - val_loss: 0.4638
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8053 - loss: 0.4027 - val_accuracy: 0.8117 - val_loss: 0.4632
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7975 - loss: 0.4138 - val_accuracy: 0.8182 - val_loss: 0.4629
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7965 - loss: 0.4222 - val_accuracy: 0.8117 - val_loss: 0.4647
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8338 - loss: 0.3995 - val_accuracy: 0.8117 - val_loss: 0.4618
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7893 - loss: 0.4343 - val_accuracy: 0.8182 - val_loss: 0.4622
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4227 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8295 - loss: 0.3863 - val_accuracy: 0.8182 - val_loss: 0.4646
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8112 - loss: 0.4044 - val_accuracy: 0.8117 - val_loss: 0.4648
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8180 - loss: 0.3962 - val_accuracy: 0.8182 - val_loss: 0.4640
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8061 - loss: 0.3962 - val_accuracy: 0.8052 - val_loss: 0.4654
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7642 - loss: 0.4311 - val_accuracy: 0.8182 - val_loss: 0.4642
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8131 - loss: 0.4040 - val_accuracy: 0.8182 - val_loss: 0.4642
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8007 - loss: 0.4184 - val_accuracy: 0.8182 - val_loss: 0.4636
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8295 - loss: 0.3922 - val_accuracy: 0.8052 - val_loss: 0.4637
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8198 - loss: 0.4023 - val_accuracy: 0.8052 - val_loss: 0.4615
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8069 - loss: 0.4353 - val_accuracy: 0.8182 - val_loss: 0.4636
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8130 - loss: 0.4075 - val_accuracy: 0.8052 - val_loss: 0.4617
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8298 - loss: 0.3905 - val_accuracy: 0.8117 - val_loss: 0.4634
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8138 - loss: 0.4173 - val_accuracy: 0.8247 - val_loss: 0.4618
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8141 - loss: 0.4008 - val_accuracy: 0.8247 - val_loss: 0.4632
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7992 - loss: 0.4151 - val_accuracy: 0.8247 - val_loss: 0.4660
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8194 - loss: 0.3905 - val_accuracy: 0.8247 - val_loss: 0.4639
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8075 - loss: 0.4045 - val_accuracy: 0.8117 - val_loss: 0.4626
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8221 - loss: 0.3828 - val_accuracy: 0.8247 - val_loss: 0.4653
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8159 - loss: 0.3965 - val_accuracy: 0.8312 - val_loss: 0.4657
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8115 - loss: 0.4233 - val_accuracy: 0.8117 - val_loss: 0.4657
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8217 - loss: 0.3923 - val_accuracy: 0.8182 - val_loss: 0.4665
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8126 - loss: 0.3964 - val_accuracy: 0.8182 - val_loss: 0.4630
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8266 - loss: 0.3955 - val_accuracy: 0.8247 - val_loss: 0.4656
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8150 - loss: 0.3972 - val_accuracy: 0.8247 - val_loss: 0.4650
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8020 - loss: 0.4215 - val_accuracy: 0.8182 - val_loss: 0.4666
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8321 - loss: 0.3764 - val_accuracy: 0.8182 - val_loss: 0.4665
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8108 - loss: 0.4217 - val_accuracy: 0.8247 - val_loss: 0.4667
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8206 - loss: 0.3937 - val_accuracy: 0.8247 - val_loss: 0.4669
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7973 - loss: 0.4348 - val_accuracy: 0.8247 - val_loss: 0.4677
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8295 - loss: 0.3865 - val_accuracy: 0.8247 - val_loss: 0.4658
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4127 - val_accuracy: 0.8312 - val_loss: 0.4657
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8065 - loss: 0.4135 - val_accuracy: 0.8182 - val_loss: 0.4669
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8312 - loss: 0.3824 - val_accuracy: 0.8247 - val_loss: 0.4662
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8212 - loss: 0.4034 - val_accuracy: 0.8182 - val_loss: 0.4658
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3880 - val_accuracy: 0.7987 - val_loss: 0.4656
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8218 - loss: 0.4009 - val_accuracy: 0.8182 - val_loss: 0.4661
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8027 - loss: 0.4163 - val_accuracy: 0.8182 - val_loss: 0.4662
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8053 - loss: 0.3976 - val_accuracy: 0.8182 - val_loss: 0.4674
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8203 - loss: 0.3894 - val_accuracy: 0.8247 - val_loss: 0.4646
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8352 - loss: 0.3884 - val_accuracy: 0.8182 - val_loss: 0.4613
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8377 - loss: 0.3727 - val_accuracy: 0.8182 - val_loss: 0.4637
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8241 - loss: 0.4000 - val_accuracy: 0.8247 - val_loss: 0.4656
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8246 - loss: 0.3911 - val_accuracy: 0.8182 - val_loss: 0.4641
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8248 - loss: 0.3985 - val_accuracy: 0.8182 - val_loss: 0.4638
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8409 - loss: 0.3620 - val_accuracy: 0.8247 - val_loss: 0.4631

# keras tuner
tuning no. of layers